@API_Route = http://localhost:5254/api/v1

### GET All Cards
GET {{API_Route}}/cards
Accept: application/json

### Post Card
POST {{API_Route}}/cards
Content-Type: application/json

{
  "title": "Card Name",
  "description": "Card Description"
}

> {%
    client.global.set("cardId", response.body._id);
%}

### Get Card
GET {{API_Route}}/cards/{{cardId}}
Accept: application/json

### Put Card
PUT {{API_Route}}/cards/{{cardId}}
Content-Type: application/json

{
  "Title": "Different Name",
  "description": "Different Description"
}

### Delete Card
DELETE {{API_Route}}/cards/{{cardId}}
Accept: application/json